language: node_js
node_js:
  - '8'
script:
  - npm install
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: a6NxY7UoFq0RD/hd2I6dZlmfRAl6gLottwe/KqSZwQ1ZhebSoygbniZ2NomqO5K0sdUzwR37aLNatgLjHnfkTo6RYf0dFnVlToQj54ZO820IjrkE7LXYbdiuHyFEGzr/T8FWFXj6DSWYPXw1oSYJJgYO4WEbP+2/Rq47UdgoMRhN3tlHyx1OkHTtZcow2ieEs8c2wdBxQhaiPT4knXFOJeP9hRjaCK/gCun0BBLdE0uFAPZgaGJj/KFr6WhoBSu2PQBXIIKgtdpjwC570ksAnGuXTWudGsaIaJvmlOOH5psIaPGsOKx7AamM3pmP7L2zmNbgpXphZUmekZ0tFoPpuqV/gCYsQ5weEo1eoZBk33xJBEgmz4BQ30cxwh1iLuHy9ZmeOY163hO5PCjIT07XUbCklzg8xxlGQRx9AWAHz/HGoaGviOB/YnBT3DlVzFRpDfQYd6gLeBrTh5vuDMCUGeObNP6p4C1tYjc7D0cM57ZY6QUc1MBhd4mf6u8P59Sxl1OcHEb6OOqBSh+Cc+eNnTJUCIo/RwHe4cyKxd4P7mdxaJzctByasGXHM07YbQlN39LUruMZu9AOFc7YtFw1NdwAaRkiImF4LIIy+uwqGub4E7vtgaoqS0KDx2TnDCmrQAW3mBlFMzY4mUzT9gccEj8Jl0hkolJe3S2zyiQm8Do=
  app: node-yu
  on:
    repo: yangyu823/node-yu