language: node_js
node_js:
- '8'
script:
- npm install
- npm test
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: 4cIjwNzpJLeUM7IYspETLmLjrS1mT4JTHynEqWoZL0qnhYzKDfLnspzyWhH9JZcldHIJgL/4llbXce4XphIvQTXNaW9by6mFVkIEZUKe9gz4JR41awuB3UvCmoO62IFisFp2iWXMULOec4ppeiyTdQEpIcjCtZCwACFSyJFaXTQRKDgXPPGKIyI0KI6yLAFTW/iJdkObgB6VH+RWCC/PP5ffIrBIGqbyjbGJEWnycYmAXToPoIQz1gDcKGdncvyz8b0vXnsy3WBysJa3OhP8HTReH5LDbKF08dSQm+swHTZH1KMD1G2OLSZtD0yO6mNdLRwN1IC0j83t7Y53EyZI6NXVCGfRd+/3QQmBjsRffMTXApncWd4ygcfaU4ot/Be+CmwzkwtDmKXjOlhgRpTk8nlRgfFZgo9GsHXhgDhPkjZLYV52qBJ3NKzinqJzUVm4YHUC1EMDMKAufPsq3GhKDcJkEUi638A4JpJDAsfhyQSrLbazra9RRMnwhH3d+8fqcKoVNAtju/wMMR8Rs86QXjOv3j3iDl52B8MacFAWENOtQ69SKNJVdG/KuKw6lGKOJQITFdI5iTyy/8fe0KlBUCkG3WNwDr7bTa9EjNcCOvZJXNnEyQCd1DXTWwVxY8TtUXQCgOW1nf0EdZ8k5rAfzo/quFa0eZK95zT6I9lqLjw=
  app: node-yu
  on:
    repo: yangyu823/node-yu
