version: '3'
services:
  app:
    build: .
    image: yangyu823/node-yu
    container_name: app
    restart: always
    ports:
      - "9999:9999"
    links:
      - mongo
#  Mongo Database setup
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./public:/public/db
    ports:
      - "27017:27017"
#  Data seed population
  mongo-seed:
    build: ./mongo
    links:
      - mongo
#  Mongo Database GUI setup
  adminmongo:
    image: "mrvautin/adminmongo"
    environment:
      - CONN_NAME=DB_CONN
      - DB_HOST=mongo
      - DB_PORT=27017
      - HOST=0.0.0.0
    ports:
      - "1234:1234"
    links:
      - mongo
