version: '3'
services:
  app:
    build: .
    image: yangyu823/node
    container_name: app
    restart: always
    ports:
      - "9999:9999"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./public:/public/db
    ports:
      - "27017:27017"